name: CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2.9

    - name: Upgrade GCC
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa -y
        sudo apt update
        sudo apt install gcc-13 g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100 --slave /usr/bin/g++ g++ /usr/bin/g++-13 --slave /usr/bin/gcov gcov /usr/bin/gcov-13

    - name: Set CXX ENV
      run: echo "CXX=g++-13" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=release -G "Ninja"

    - name: Build
      run: cd build && cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache .. && ninja